import json
import re
import traceback

from pymongo import UpdateOne
import requests
from update.update_items import create_item_description

from dotenv import load_dotenv
import os
from helper_funcs.helper_imports import db, hero_list

load_dotenv()

api_key = os.environ.get("STRATZ_API_KEY")
stratz_abilities_constant = None


def parse_talents(datamined_abilities, talent_json):
    hero_talents = {}
    for talent in talent_json:
        hint = [talent["name_loc"]]
        try:
            desc = create_item_description(hint, datamined_abilities, talent["name"])
            if desc == hint:
                pass
            talent["name_loc"] = re.sub(r"-- ", "", desc[0])
        except Exception:
            displayName = talents_from_stratz(talent["id"])
            if displayName:
                talent["name_loc"] = displayName
        hero_talents[str(talent["id"])] = talent
    return hero_talents


def talents_from_stratz(_id: int) -> str | None:
    query = """
     {
        constants {
            abilities {
                id
                isTalent
                name
                language {
                    displayName
                }
            }
        }
    }
    """
    request_data = {"query": query}
    headers = {
        "content-type": "application/json",
        "Authorization": f"Bearer {api_key}",
        'User-Agent': 'STRATZ_API',
    }
    url = "https://api.stratz.com/graphql"
    global stratz_abilities_constant
    if not stratz_abilities_constant:
        req = requests.post(url=url, headers=headers, json=request_data)
        if req.status_code != 200:

            return None
        print("stratz constants requested")
        stratz_abilities_constant = req.json()
    abilities = stratz_abilities_constant["data"]["constants"]["abilities"]
    for ability in abilities:
        if ability["id"] == _id:
            if not ability["language"]:
                print(ability["name"])
                continue
            return ability["language"]["displayName"]
    return None

def update_hero_talents(talents):
    for i, talent in enumerate(talents):
        if i % 2 == 0:
            talents[talent]["slot"] = i + 1
        else:
            talents[talent]["slot"] = i - 1
    # talent slots: 1 0 3 2 5 4 7 6
    return talents
def update_talents():
    talent_updates = []
    for hero in hero_list:
        print('update talents for', hero["name"])
        # db_methods.insert_talent_order(hero['id'])

        talents = db["hero_stats"].find_one({"hero": hero["name"]})["talents"]
        for i, talent in enumerate(talents):
            if i % 2 == 0:
                talents[talent]["slot"] = i + 1
            else:
                talents[talent]["slot"] = i - 1
        # 1 0 3 2 5 4 7 6

        # short_talents = update_short_talents(talents)
        # print(short_talents)
        # db["talents"].find_one_and_update(
        #     {"hero": switcher(hero["name"])},
        #     {"$set": {"talents": short_talents}},
        #     upsert=True,
        # )
        # print(talents)
        talent_updates.append(extract_special_values(talents, hero["name"]))
    if talent_updates:
         db['hero_stats'].bulk_write(talent_updates)


def extract_special_values(talents, hero):
    for k in talents:
        if "{" not in talents[k]["name_loc"]:
            continue
        try:
            special_values = talents[k]["special_values"]
            test_string = talents[k]["name_loc"]
            clean = val(test_string, special_values)
            talents[k]["name_loc"] = clean
        except Exception:
            print(
                "Exception: ", hero, k, talents[k]["name_loc"], traceback.format_exc()
            )
    return UpdateOne({"hero": hero}, {"$set": {"talents": talents}}, upsert=True)


def val(text, special_values):
    # print(text)
    pattern = re.compile("s:(\w*)")
    result = ""
    if len(special_values) == 0:
        return text.replace(r"{s:.*}", "")
    for value in special_values:
        special_val = ""
        if len(result) > 0:
            text = result
        if "s:" not in text:
            return text
        match = pattern.search(text).group(1)
        if (
            value["name"] == match
            or value["name"] == "value"
            and len(special_values) == 1
        ):
            if len(value["values_float"]) > 0:
                special_val += f"{round(value['values_float'][0], 2)}"
            else:
                special_val += str(value["values_int"][0])
            if value["is_percentage"]:
                special_val += "%"
            regex = "{s:" + match + "}"
            result = re.sub(regex, special_val, text)
    if result == "":
        return re.sub(r"{s:.*}s?%?", "", text)
    return result


if __name__ == "__main__":
    with open('update/test_files/7.37d_abilities.json', 'r') as f:
        data = json.load(f)
        parse_talents(
            datamined_abilities=data,
            talent_json=[
                {
                    "id": 6016,
                    "name": "special_bonus_attack_speed_25",
                    "name_loc": "+{s:value} Attack Speed",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "value",
                            "values_float": [25],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 7132,
                    "name": "special_bonus_mp_regen_150",
                    "name_loc": "+{s:value} Mana Regen",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "value",
                            "values_float": [1.5],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 1078,
                    "name": "special_bonus_unique_bristleback_5",
                    "name_loc": "+{s:bonus_AbilityCastRange} Goo Cast Range",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 1079,
                    "name": "special_bonus_unique_bristleback_6",
                    "name_loc": "+{s:bonus_back_damage_reduction}%/{s:bonus_side_damage_reduction}% Bristleback Back/Side Damage Reduction",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 6308,
                    "name": "special_bonus_hp_regen_25",
                    "name_loc": "+{s:value} Health Regen",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "value",
                            "values_float": [25],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 6360,
                    "name": "special_bonus_unique_bristleback_2",
                    "name_loc": "+{s:bonus_quill_stack_damage} Quill Stack Damage",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 434,
                    "name": "special_bonus_spell_lifesteal_12",
                    "name_loc": "+{s:value}% Spell Lifesteal",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "value",
                            "values_float": [12],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
                {
                    "id": 6615,
                    "name": "special_bonus_unique_bristleback_3",
                    "name_loc": "+{s:bonus_damage_per_stack} Warpath Damage Per Stack",
                    "desc_loc": "",
                    "lore_loc": "",
                    "notes_loc": [],
                    "shard_loc": "",
                    "scepter_loc": "",
                    "facets_loc": ["", "", ""],
                    "type": 2,
                    "behavior": "2",
                    "target_team": 0,
                    "target_type": 0,
                    "flags": 0,
                    "damage": 0,
                    "immunity": 0,
                    "dispellable": 0,
                    "max_level": 4,
                    "cast_ranges": [0],
                    "cast_points": [0],
                    "channel_times": [0],
                    "cooldowns": [0],
                    "durations": [0],
                    "damages": [0, 0, 0, 0],
                    "mana_costs": [0],
                    "gold_costs": [],
                    "health_costs": [],
                    "special_values": [
                        {
                            "name": "AbilityCastRange",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChannelTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityDuration",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCastPoint",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCharges",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityChargeRestoreTime",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityManaCost",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                        {
                            "name": "AbilityCooldown",
                            "values_float": [0],
                            "is_percentage": False,
                            "heading_loc": "",
                            "bonuses": [],
                            "values_shard": [],
                            "values_scepter": [],
                            "facet_bonus": {"name": "", "values": [], "operation": 0},
                            "required_facet": "",
                        },
                    ],
                    "is_item": False,
                    "ability_has_scepter": False,
                    "ability_has_shard": False,
                    "ability_is_granted_by_scepter": False,
                    "ability_is_granted_by_shard": False,
                    "ability_is_innate": False,
                    "item_cost": 0,
                    "item_initial_charges": 0,
                    "item_neutral_tier": 4294967295,
                    "item_stock_max": 0,
                    "item_stock_time": 0,
                    "item_quality": 0,
                },
            ],
        )
